<?php

namespace DeparturesBoardBundle\Repository;

/**
 * BusdeparturetimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusdeparturetimeRepository extends \Doctrine\ORM\EntityRepository
{
}
