<?php

namespace DeparturesBoardBundle\Repository;

/**
 * BusdepartureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusdepartureRepository extends \Doctrine\ORM\EntityRepository
{
}
