<?php

namespace DeparturesBoardBundle\Repository;

/**
 * BusstopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusstopRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getBusstops()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT b.name, b.code FROM DeparturesBoardBundle:Busstop b')
            ->getResult();
    }
    
}
