<?php

namespace DeparturesBoardBundle\Repository;

/**
 * BusstopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusstopRepository extends \Doctrine\ORM\EntityRepository
{
}
