departures_page:
    path:     /
    defaults: { _controller: DeparturesBoardBundle:Departures:show }

departures_api:
    resource: "@DeparturesBoardBundle/Controller/ApiController.php"
    prefix: /api/
    type: rest
    options:
        expose: true
    