services:
    departures_board.importer:
            class: DeparturesBoardBundle\DependencyInjection\Importer
            arguments: 
                entityManager: "@doctrine.orm.entity_manager"
    cache:
        class: Doctrine\Common\Cache\ArrayCache
#    departures_board.example:
#        class: DeparturesBoardBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
